@ScanUnpload.Api.Client.Test_HostAddress = https://localhost:7185

GET {{ScanUnpload.Api.Client.Test_HostAddress}}/token/
Accept: application/json
###

GET {{ScanUnpload.Api.Client.Test_HostAddress}}/cached-token/
Accept: application/json

###
POST {{ScanUnpload.Api.Client.Test_HostAddress}}/scanupload-api/session/create
Accept:application/json
Content-Type: application/json 

{ 

}

###
GET {{ScanUnpload.Api.Client.Test_HostAddress}}/scanupload-api/token
Accept:application/json